---
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: mixed-line-ending
      - id: detect-private-key
      - id: no-commit-to-branch
        args:
          - -b master
      - id: no-commit-to-branch
        args:
          - -b main
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.13.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        stages: [commit]
